[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  # Increase timeout for database operations
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 