[build]
  command = "npm install && npx svelte-kit sync && echo '=== STARTING BUILD ===' && npm run build || { echo '=== BUILD FAILED - DETAILED ERROR ===' && echo 'Package.json scripts:' && cat package.json | grep -A 10 '\"scripts\"' && echo 'Vite config:' && cat vite.config.ts && echo 'SvelteKit config:' && cat svelte.config.js && echo 'Node modules @sveltejs contents:' && ls -la node_modules/@sveltejs/ 2>/dev/null && echo 'Generated .svelte-kit:' && ls -la .svelte-kit/ 2>/dev/null && echo 'Final npm logs:' && cat /opt/buildhome/.npm/_logs/* 2>/dev/null | tail -50 && false; }"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  # Increase timeout for database operations
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 