[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Build hooks - run migrations before build
[[plugins]]
  package = "@netlify/plugin-functions"

# Environment variables that should be set in Netlify dashboard:
# ENCRYPTION_KEY - 64-character hex string for data encryption
# DATABASE_URL - PostgreSQL connection string
# NODE_ENV - set to "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SvelteKit routing - redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development preview settings
[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"

# Build command will run migrations automatically
# Migration logs will be visible in Netlify build logs
# Database state is checked before applying any migrations
# All operations are wrapped in transactions for safety
