[build]
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

# Environment variables that should be set in Netlify dashboard:
# ENCRYPTION_KEY - 64-character hex string for data encryption
# DATABASE_URL - PostgreSQL connection string
# NODE_ENV - set to "production"

# Development preview settings
[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"
